name-template: $PREVIOUS_TAG
tag-template: $PREVIOUS_TAG
categories:
  - title: '変更履歴'
exclude-labels:
  - 'ignore-for-release-note'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
template: |
  $CHANGES
footer: |

  ## 🌱 すべての変更点

  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
